/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ass2test;

import java.awt.CardLayout;
import Model.Account;
import Model.ChequeAccount;
import Model.FixedAccount;
import Model.NetSaverAccount;
import Model.SavingsAccount;
import java.util.List;
/**
 *
 * @author 7208
 */
public class MainScreen extends javax.swing.JFrame {

    /**
     * Creates new form MainScreen
     */
    private Account[] accounts =null; 
    public MainScreen(Account[] accounts) {
        
        this.accounts=accounts;
        
        
        
        
        initComponents();
    }
    String currentCard="loginCard"; //initiate current card to login card
    
    Account acc;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        mainPanel = new javax.swing.JPanel();
        LoginPanel = new javax.swing.JPanel();
        textField1 = new javax.swing.JTextField();
        textLabel2 = new javax.swing.JLabel();
        textLabel1 = new javax.swing.JLabel();
        errorText = new javax.swing.JLabel();
        passwordField1 = new javax.swing.JPasswordField();
        WithdrawPanel = new javax.swing.JPanel();
        textLabel3 = new javax.swing.JLabel();
        withdrawTextField = new javax.swing.JTextField();
        errorText1 = new javax.swing.JLabel();
        BalanceInquiryPanel = new javax.swing.JPanel();
        textLabel4 = new javax.swing.JLabel();
        textLabel5 = new javax.swing.JLabel();
        textLabel6 = new javax.swing.JLabel();
        textLabel7 = new javax.swing.JLabel();
        textLabel8 = new javax.swing.JLabel();
        textLabel9 = new javax.swing.JLabel();
        textLabel10 = new javax.swing.JLabel();
        textLabel11 = new javax.swing.JLabel();
        setLimitTextField = new javax.swing.JTextField();
        setLimitLabel = new javax.swing.JLabel();
        AfterCashOutPanel = new javax.swing.JPanel();
        withdrawnLabel = new javax.swing.JLabel();
        cashOutAmountLabel = new javax.swing.JLabel();
        newBalanceLabel = new javax.swing.JLabel();
        withdrawnLabel1 = new javax.swing.JLabel();
        DepositPanel = new javax.swing.JPanel();
        depositTextField = new javax.swing.JTextField();
        depositLabel = new javax.swing.JLabel();
        AfterCashInPanel = new javax.swing.JPanel();
        depositedLabel = new javax.swing.JLabel();
        cashInAmountLabel = new javax.swing.JLabel();
        newBalanceLabel1 = new javax.swing.JLabel();
        withdrawnLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        withdrawButton = new javax.swing.JButton();
        enterButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        inquiryBtn = new javax.swing.JButton();
        numButton1 = new javax.swing.JButton();
        numButton2 = new javax.swing.JButton();
        numButton3 = new javax.swing.JButton();
        numButton4 = new javax.swing.JButton();
        numButton6 = new javax.swing.JButton();
        numButton5 = new javax.swing.JButton();
        numButton7 = new javax.swing.JButton();
        numButton8 = new javax.swing.JButton();
        numButton9 = new javax.swing.JButton();
        numButton0 = new javax.swing.JButton();
        numButtonDecimal = new javax.swing.JButton();
        numButtonClear = new javax.swing.JButton();
        depositButton = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 153));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(java.awt.Color.gray);
        setMaximumSize(new java.awt.Dimension(0, 0));

        mainPanel.setLayout(new java.awt.CardLayout());

        LoginPanel.setBackground(new java.awt.Color(51, 51, 51));

        textField1.setBackground(new java.awt.Color(204, 255, 255));
        textField1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        textField1.setDisabledTextColor(new java.awt.Color(204, 255, 255));

        textLabel2.setForeground(new java.awt.Color(204, 255, 255));
        textLabel2.setText("Enter Pin Number: ");

        textLabel1.setForeground(new java.awt.Color(204, 255, 255));
        textLabel1.setText("Enter Account Number: ");

        errorText.setForeground(new java.awt.Color(255, 0, 0));

        passwordField1.setBackground(new java.awt.Color(204, 255, 255));
        passwordField1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        javax.swing.GroupLayout LoginPanelLayout = new javax.swing.GroupLayout(LoginPanel);
        LoginPanel.setLayout(LoginPanelLayout);
        LoginPanelLayout.setHorizontalGroup(
            LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginPanelLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(errorText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(LoginPanelLayout.createSequentialGroup()
                        .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textLabel1)
                            .addComponent(textLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(passwordField1)
                            .addComponent(textField1, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE))))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        LoginPanelLayout.setVerticalGroup(
            LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textLabel1)
                    .addComponent(textField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textLabel2)
                    .addComponent(passwordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(errorText, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        mainPanel.add(LoginPanel, "loginCard");

        WithdrawPanel.setBackground(new java.awt.Color(51, 51, 51));

        textLabel3.setForeground(new java.awt.Color(204, 255, 255));
        textLabel3.setText("Withdraw: ");

        withdrawTextField.setBackground(new java.awt.Color(204, 255, 255));

        errorText1.setForeground(new java.awt.Color(204, 255, 255));

        javax.swing.GroupLayout WithdrawPanelLayout = new javax.swing.GroupLayout(WithdrawPanel);
        WithdrawPanel.setLayout(WithdrawPanelLayout);
        WithdrawPanelLayout.setHorizontalGroup(
            WithdrawPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, WithdrawPanelLayout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(textLabel3)
                .addGap(18, 18, 18)
                .addComponent(withdrawTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
            .addGroup(WithdrawPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, WithdrawPanelLayout.createSequentialGroup()
                    .addContainerGap(40, Short.MAX_VALUE)
                    .addComponent(errorText1, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(39, Short.MAX_VALUE)))
        );
        WithdrawPanelLayout.setVerticalGroup(
            WithdrawPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WithdrawPanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(WithdrawPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(withdrawTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textLabel3))
                .addContainerGap(97, Short.MAX_VALUE))
            .addGroup(WithdrawPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, WithdrawPanelLayout.createSequentialGroup()
                    .addContainerGap(79, Short.MAX_VALUE)
                    .addComponent(errorText1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(56, Short.MAX_VALUE)))
        );

        mainPanel.add(WithdrawPanel, "withdrawCard");

        BalanceInquiryPanel.setBackground(new java.awt.Color(51, 51, 51));
        BalanceInquiryPanel.setForeground(new java.awt.Color(204, 255, 255));

        textLabel4.setForeground(new java.awt.Color(204, 255, 255));
        textLabel4.setText("Account Number: ");

        textLabel5.setForeground(new java.awt.Color(204, 255, 255));
        textLabel5.setText("Account Type:");

        textLabel6.setForeground(new java.awt.Color(204, 255, 255));
        textLabel6.setText("Account Interest: ");

        textLabel7.setForeground(new java.awt.Color(204, 255, 255));
        textLabel7.setText("Current Balance: ");

        textLabel8.setForeground(new java.awt.Color(204, 255, 255));
        textLabel8.setText("123");

        textLabel9.setForeground(new java.awt.Color(204, 255, 255));
        textLabel9.setText("123");

        textLabel10.setForeground(new java.awt.Color(204, 255, 255));
        textLabel10.setText("123");

        textLabel11.setForeground(new java.awt.Color(204, 255, 255));
        textLabel11.setText("123");

        setLimitTextField.setBackground(new java.awt.Color(204, 255, 255));
        setLimitTextField.setEnabled(false);

        setLimitLabel.setForeground(new java.awt.Color(204, 255, 255));

        javax.swing.GroupLayout BalanceInquiryPanelLayout = new javax.swing.GroupLayout(BalanceInquiryPanel);
        BalanceInquiryPanel.setLayout(BalanceInquiryPanelLayout);
        BalanceInquiryPanelLayout.setHorizontalGroup(
            BalanceInquiryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BalanceInquiryPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(BalanceInquiryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BalanceInquiryPanelLayout.createSequentialGroup()
                        .addComponent(textLabel6)
                        .addGap(1, 1, 1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BalanceInquiryPanelLayout.createSequentialGroup()
                        .addComponent(textLabel5)
                        .addGap(21, 21, 21))
                    .addComponent(textLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(BalanceInquiryPanelLayout.createSequentialGroup()
                        .addComponent(textLabel7)
                        .addGap(3, 3, 3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 287, Short.MAX_VALUE)
                .addGroup(BalanceInquiryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(textLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(textLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(textLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(29, 29, 29))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BalanceInquiryPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(setLimitLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(setLimitTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(138, 138, 138))
        );
        BalanceInquiryPanelLayout.setVerticalGroup(
            BalanceInquiryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BalanceInquiryPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(BalanceInquiryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textLabel4)
                    .addComponent(textLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BalanceInquiryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textLabel5)
                    .addComponent(textLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BalanceInquiryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textLabel6)
                    .addComponent(textLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BalanceInquiryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textLabel7)
                    .addComponent(textLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(BalanceInquiryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(setLimitTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(setLimitLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        mainPanel.add(BalanceInquiryPanel, "inquiryCard");

        AfterCashOutPanel.setBackground(new java.awt.Color(51, 51, 51));

        withdrawnLabel.setForeground(new java.awt.Color(204, 255, 255));
        withdrawnLabel.setText("withdrawn: ");

        cashOutAmountLabel.setForeground(new java.awt.Color(204, 255, 255));

        newBalanceLabel.setForeground(new java.awt.Color(204, 255, 255));

        withdrawnLabel1.setForeground(new java.awt.Color(204, 255, 255));
        withdrawnLabel1.setText("New Balance: ");

        javax.swing.GroupLayout AfterCashOutPanelLayout = new javax.swing.GroupLayout(AfterCashOutPanel);
        AfterCashOutPanel.setLayout(AfterCashOutPanelLayout);
        AfterCashOutPanelLayout.setHorizontalGroup(
            AfterCashOutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AfterCashOutPanelLayout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addGroup(AfterCashOutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(withdrawnLabel1)
                    .addComponent(withdrawnLabel))
                .addGap(18, 18, 18)
                .addGroup(AfterCashOutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cashOutAmountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newBalanceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        AfterCashOutPanelLayout.setVerticalGroup(
            AfterCashOutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AfterCashOutPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(AfterCashOutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(withdrawnLabel)
                    .addComponent(cashOutAmountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AfterCashOutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(withdrawnLabel1)
                    .addComponent(newBalanceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(79, Short.MAX_VALUE))
        );

        withdrawnLabel1.getAccessibleContext().setAccessibleName("withdrawnLabel");

        mainPanel.add(AfterCashOutPanel, "afterCashOutCard");

        DepositPanel.setBackground(new java.awt.Color(51, 51, 51));

        depositTextField.setBackground(new java.awt.Color(204, 255, 255));

        depositLabel.setForeground(new java.awt.Color(204, 255, 255));
        depositLabel.setText("Deposit: ");

        javax.swing.GroupLayout DepositPanelLayout = new javax.swing.GroupLayout(DepositPanel);
        DepositPanel.setLayout(DepositPanelLayout);
        DepositPanelLayout.setHorizontalGroup(
            DepositPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DepositPanelLayout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(depositLabel)
                .addGap(18, 18, 18)
                .addComponent(depositTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(97, Short.MAX_VALUE))
        );
        DepositPanelLayout.setVerticalGroup(
            DepositPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DepositPanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(DepositPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(depositTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(depositLabel))
                .addContainerGap(97, Short.MAX_VALUE))
        );

        mainPanel.add(DepositPanel, "depositCard");

        AfterCashInPanel.setBackground(new java.awt.Color(51, 51, 51));

        depositedLabel.setForeground(new java.awt.Color(204, 255, 255));
        depositedLabel.setText("Deposited: ");

        cashInAmountLabel.setForeground(new java.awt.Color(204, 255, 255));

        newBalanceLabel1.setForeground(new java.awt.Color(204, 255, 255));

        withdrawnLabel3.setForeground(new java.awt.Color(204, 255, 255));
        withdrawnLabel3.setText("New Balance: ");

        javax.swing.GroupLayout AfterCashInPanelLayout = new javax.swing.GroupLayout(AfterCashInPanel);
        AfterCashInPanel.setLayout(AfterCashInPanelLayout);
        AfterCashInPanelLayout.setHorizontalGroup(
            AfterCashInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AfterCashInPanelLayout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addGroup(AfterCashInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(withdrawnLabel3)
                    .addComponent(depositedLabel))
                .addGap(18, 18, 18)
                .addGroup(AfterCashInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cashInAmountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newBalanceLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        AfterCashInPanelLayout.setVerticalGroup(
            AfterCashInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AfterCashInPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(AfterCashInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(depositedLabel)
                    .addComponent(cashInAmountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AfterCashInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(withdrawnLabel3)
                    .addComponent(newBalanceLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(79, Short.MAX_VALUE))
        );

        mainPanel.add(AfterCashInPanel, "afterCashInCard");

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        withdrawButton.setBackground(new java.awt.Color(204, 255, 255));
        withdrawButton.setText("Withdraw");
        withdrawButton.setEnabled(false);
        withdrawButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withdrawButtonActionPerformed(evt);
            }
        });

        enterButton.setBackground(new java.awt.Color(204, 255, 255));
        enterButton.setText("Enter");
        enterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterButtonActionPerformed(evt);
            }
        });

        backButton.setBackground(new java.awt.Color(204, 255, 255));
        backButton.setText("Back");
        backButton.setEnabled(false);
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        inquiryBtn.setBackground(new java.awt.Color(204, 255, 255));
        inquiryBtn.setText("Balance Inquiry");
        inquiryBtn.setEnabled(false);
        inquiryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inquiryBtnActionPerformed(evt);
            }
        });

        numButton1.setBackground(new java.awt.Color(204, 255, 255));
        numButton1.setText("1");
        numButton1.setEnabled(false);
        numButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numButton1ActionPerformed(evt);
            }
        });

        numButton2.setBackground(new java.awt.Color(204, 255, 255));
        numButton2.setText("2");
        numButton2.setEnabled(false);
        numButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numButton2ActionPerformed(evt);
            }
        });

        numButton3.setBackground(new java.awt.Color(204, 255, 255));
        numButton3.setText("3");
        numButton3.setEnabled(false);
        numButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numButton3ActionPerformed(evt);
            }
        });

        numButton4.setBackground(new java.awt.Color(204, 255, 255));
        numButton4.setText("4");
        numButton4.setEnabled(false);
        numButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numButton4ActionPerformed(evt);
            }
        });

        numButton6.setBackground(new java.awt.Color(204, 255, 255));
        numButton6.setText("6");
        numButton6.setEnabled(false);
        numButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numButton6ActionPerformed(evt);
            }
        });

        numButton5.setBackground(new java.awt.Color(204, 255, 255));
        numButton5.setText("5");
        numButton5.setEnabled(false);
        numButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numButton5ActionPerformed(evt);
            }
        });

        numButton7.setBackground(new java.awt.Color(204, 255, 255));
        numButton7.setText("7");
        numButton7.setEnabled(false);
        numButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numButton7ActionPerformed(evt);
            }
        });

        numButton8.setBackground(new java.awt.Color(204, 255, 255));
        numButton8.setText("8");
        numButton8.setEnabled(false);
        numButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numButton8ActionPerformed(evt);
            }
        });

        numButton9.setBackground(new java.awt.Color(204, 255, 255));
        numButton9.setText("9");
        numButton9.setEnabled(false);
        numButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numButton9ActionPerformed(evt);
            }
        });

        numButton0.setBackground(new java.awt.Color(204, 255, 255));
        numButton0.setText("0");
        numButton0.setEnabled(false);
        numButton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numButton0ActionPerformed(evt);
            }
        });

        numButtonDecimal.setBackground(new java.awt.Color(204, 255, 255));
        numButtonDecimal.setText(".");
        numButtonDecimal.setEnabled(false);
        numButtonDecimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numButtonDecimalActionPerformed(evt);
            }
        });

        numButtonClear.setBackground(new java.awt.Color(204, 255, 255));
        numButtonClear.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        numButtonClear.setText("clr");
        numButtonClear.setEnabled(false);
        numButtonClear.setMargin(new java.awt.Insets(2, 10, 2, 10));
        numButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numButtonClearActionPerformed(evt);
            }
        });

        depositButton.setBackground(new java.awt.Color(204, 255, 255));
        depositButton.setText("Deposit");
        depositButton.setEnabled(false);
        depositButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(numButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(numButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(numButton6))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(numButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(numButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(numButton3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(numButton7)
                            .addComponent(numButton0))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(numButtonDecimal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(numButton8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(numButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(numButtonClear, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(enterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(backButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(inquiryBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(withdrawButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(depositButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(52, 52, 52))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(numButton1)
                            .addComponent(numButton2)
                            .addComponent(numButton3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(numButton4)
                            .addComponent(numButton6)
                            .addComponent(numButton5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(numButton8)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(numButton9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(numButtonClear, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(enterButton)
                                    .addComponent(backButton)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(numButton7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(numButton0)
                                    .addComponent(numButtonDecimal)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(withdrawButton)
                            .addComponent(depositButton))
                        .addGap(18, 18, 18)
                        .addComponent(inquiryBtn)))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterButtonActionPerformed
        switch(currentCard)
        {
            case "loginCard":
            {
                if(isValidAccount(textField1.getText(), new String(passwordField1.getPassword())))
                {
                    //everytime you click the button enter after a login
                    /**
                     * the keypads won't work and the withdraw setting will not work
                     */
                    setLimitLabel.setText("");
                    setLimitTextField.setEnabled(false);
                    numButton0.setEnabled(false);
                    numButton1.setEnabled(false);
                    numButton2.setEnabled(false);
                    numButton3.setEnabled(false);
                    numButton4.setEnabled(false);
                    numButton5.setEnabled(false);            
                    numButton6.setEnabled(false);
                    numButton7.setEnabled(false);
                    numButton8.setEnabled(false);
                    numButton9.setEnabled(false);
                    numButtonDecimal.setEnabled(false);
                    numButtonClear.setEnabled(false);
                    inquiryBtn.setEnabled(false);
                    enterButton.setEnabled(false);
                
                    //making a cLayout which is a new cardlayout that reprsents the mainPanel
                    CardLayout cLayout= (CardLayout)mainPanel.getLayout(); 
                    /**
                     * //this is to show the cardlayout which is cLayout to either 
                     * anycards or panel you want. in this case it is showing
                     * inquiryCard when the enter button is clicked
                     */
                    cLayout.show(mainPanel,"inquiryCard"); 
                    //replacing the current card state to inquiryCard
                    currentCard="inquiryCard";
                    /**
                     * This is to set the buttons to reactivate after the the login is validated.
                     */
                    depositButton.setEnabled(true);
                    withdrawButton.setEnabled(true);
                    backButton.setEnabled(true);
                    //setting the account number and type to the labels
                    textLabel8.setText(acc.getAccNum());
                    textLabel9.setText(acc.getAccType());
                    //getting the value of interest rate which is a float converting it to string and display to user
                    textLabel10.setText(String.valueOf(acc.getInterestRate()));
                    textLabel11.setText(String.valueOf(acc.getNewBalance()));
                    //if the account type is savings, then set the labels to be true and active
                    //users can set their withdrawal limit.
                    if(acc.getAccType().equalsIgnoreCase("savings"))
                    {
                        setLimitLabel.setText("Set Limit");
                        setLimitTextField.setEnabled(true);
                    }
                    errorText.setText("");
                    break;
                }
                else
                {
                    errorText.setText("Error, please key in your valid account");
                    break;
                }
                
                
            }
            case "withdrawCard":
            {
                //if the account type is savings, do this
                if(acc.getAccType().equalsIgnoreCase("savings"))
                    {
                        //setting the withdrawal limit to what users desire.
                        acc.setWithdrawalLimit(Integer.parseInt(setLimitTextField.getText()));
                    }
                //If ther withdraw amount is not 10 or 30 dollars, then proceed
                    if(withdrawTextField.getText()!="10"||withdrawTextField.getText()!="30")
                    {
                        /**
                         * if the amount requested to be withdrawn is more 
                         * than the balance, then display error message.
                         * Else proceed
                         */
                        if(Float.parseFloat(withdrawTextField.getText())>acc.getNewBalance()||Float.parseFloat(withdrawTextField.getText())>acc.getWithdrawalLimit())
                        {
                            errorText1.setText("Error, please key in less then your balance or withdraw limit");
                            break;
                        }
                        else
                        {  
                            /**
                             * getting the amount user wants to withdraw
                             * and setting it to the super class of "Account"
                             * */
                            acc.setCashOut(Float.parseFloat(withdrawTextField.getText()));
                            //Once the enter button is clicked and there is no 
                            //problem, then change the card to afterCashOut
                            //Where values will be displayed. Assuming we are
                            //currently at withdrawCard which is normally after inquiryCard
                            CardLayout cLayout= (CardLayout)mainPanel.getLayout(); 
                            cLayout.show(mainPanel,"afterCashOutCard"); 
                            currentCard="afterCashOutCard";
                            //call the function to execute some calculation
                            acc.getCashOutBalance();
                            //call the function to execute some calculation
                            cashOutAmountLabel.setText(String.valueOf(acc.getCashOut()));
                            /**
                            * Show the new balance after deposit and withdraw together
                            */
                            newBalanceLabel.setText(String.valueOf(acc.getNewBalance()));
                            withdrawButton.setEnabled(false);
                            inquiryBtn.setEnabled(true);
                            errorText1.setText("");
                            break;
                        }
                        
                    }
                    else
                    {
                        //display this when users what to cash out 10 or 30 dollars.
                        errorText1.setText("Error, You can only casah out 20, 50 and 100 dollars note");
                        break;
                    }
                    
                   
                
                 
            }
            case "depositCard":
            {
                    //set the deposit to what users desire.
                    acc.setDeposit(Float.parseFloat(depositTextField.getText()));
                    //Once the enter button is clicked and there is no 
                    //problem, then change the card to afterCashIn
                    //Where values will be displayed. Assuming we are now at 
                    //depositCard which is normally after inquiryCard
                    CardLayout cLayout= (CardLayout)mainPanel.getLayout(); 
                    cLayout.show(mainPanel,"afterCashInCard"); 
                    currentCard="afterCashInCard";
                    //call the function to execute some calculation
                    acc.getDepositBalance();
                    //show the deposit that you have previously made
                    cashInAmountLabel.setText(String.valueOf(acc.getDeposit()));
                    /**
                     * Show the new balance after deposit and withdraw together
                     */
                    newBalanceLabel1.setText(String.valueOf(acc.getNewBalance()));
                    withdrawButton.setEnabled(true);
                    inquiryBtn.setEnabled(true);
                   
                
                 break;
            }
            default:
                break;
            
        }
        
    }//GEN-LAST:event_enterButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        //making a cLayout which is a new cardlayout that reprsents the mainPanel
        CardLayout cLayout= (CardLayout)mainPanel.getLayout(); 
        //setting everything to original position
        numButton0.setEnabled(false);
        numButton1.setEnabled(false);
        numButton2.setEnabled(false);
        numButton3.setEnabled(false);
        numButton4.setEnabled(false);
        numButton5.setEnabled(false);            
        numButton6.setEnabled(false);
        numButton7.setEnabled(false);
        numButton8.setEnabled(false);
        numButton9.setEnabled(false);
        numButtonDecimal.setEnabled(false);
        numButtonClear.setEnabled(false);
        withdrawButton.setEnabled(false);
        inquiryBtn.setEnabled(false);
        depositButton.setEnabled(false);
        enterButton.setEnabled(true);
        textField1.setText("");
        passwordField1.setText("");
        /*this is to show the cardlayout which is cLayout to either anycards or 
        panel you want. in this case it is showing loginCard when the back button is clicked*/
        //make the panel to login card again
        cLayout.show(mainPanel,"loginCard"); 
        //current card will now be loginCard
        currentCard="loginCard";
    }//GEN-LAST:event_backButtonActionPerformed

    private void withdrawButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withdrawButtonActionPerformed
            /*this is to show the cardlayout which is cLayout to either anycards or 
            panel you want. in this case it is showing withdrawCard when the back button is clicked*/
            CardLayout cLayout= (CardLayout)mainPanel.getLayout(); 
            cLayout.show(mainPanel,"withdrawCard");
            currentCard="withdrawCard";
            withdrawButton.setEnabled(false);
            depositButton.setEnabled(false);
            enterButton.setEnabled(true);
            numButton0.setEnabled(true);
            numButton1.setEnabled(true);
            numButton2.setEnabled(true);
            numButton3.setEnabled(true);
            numButton4.setEnabled(true);
            numButton5.setEnabled(true);            
            numButton6.setEnabled(true);
            numButton7.setEnabled(true);
            numButton8.setEnabled(true);
            numButton9.setEnabled(true);
            numButtonDecimal.setEnabled(true);
            numButtonClear.setEnabled(true);
            withdrawTextField.setText("");
                
    }//GEN-LAST:event_withdrawButtonActionPerformed

    private void inquiryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inquiryBtnActionPerformed
        /**
         * setting the keypad to false everytime you call the inquiry button
         */            
        numButton0.setEnabled(false);
        numButton1.setEnabled(false);
        numButton2.setEnabled(false);
        numButton3.setEnabled(false);
        numButton4.setEnabled(false);
        numButton5.setEnabled(false);            
        numButton6.setEnabled(false);
        numButton7.setEnabled(false);
        numButton8.setEnabled(false);
        numButton9.setEnabled(false);
        numButtonDecimal.setEnabled(false);
        numButtonClear.setEnabled(false);        
        //setting new balance after the deposit and cash out
        textLabel11.setText(String.valueOf(acc.getNewBalance()));
        //selecting the current layout and change to inquiryCard after clicking the inquiry card
        CardLayout inquiryLayout= (CardLayout)mainPanel.getLayout();
        inquiryLayout.show(mainPanel,"inquiryCard");
        currentCard="inquiryCard"; 
        //setting the buttons to enabled
        withdrawButton.setEnabled(true);
        depositButton.setEnabled(true);
    }//GEN-LAST:event_inquiryBtnActionPerformed

    private void numButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numButton4ActionPerformed
        //add the number to the current field. Same to others
        if(currentCard=="withdrawCard")
        {
            withdrawTextField.setText(withdrawTextField.getText()+"4");
        }
        else if(currentCard=="depositCard")
        {
            depositTextField.setText(depositTextField.getText()+"4");
        }
        
    }//GEN-LAST:event_numButton4ActionPerformed

    private void numButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numButton1ActionPerformed
        if(currentCard=="withdrawCard")
        {
            withdrawTextField.setText(withdrawTextField.getText()+"1");
        }
        else if(currentCard=="depositCard")
        {
            depositTextField.setText(depositTextField.getText()+"1");
        }
    }//GEN-LAST:event_numButton1ActionPerformed

    private void numButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numButton2ActionPerformed
        if(currentCard=="withdrawCard")
        {
            withdrawTextField.setText(withdrawTextField.getText()+"2");
        }
        else if(currentCard=="depositCard")
        {
            depositTextField.setText(depositTextField.getText()+"2");
        }
    }//GEN-LAST:event_numButton2ActionPerformed

    private void numButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numButton3ActionPerformed
        if(currentCard=="withdrawCard")
        {
            withdrawTextField.setText(withdrawTextField.getText()+"3");
        }
        else if(currentCard=="depositCard")
        {
            depositTextField.setText(depositTextField.getText()+"3");
        }
    }//GEN-LAST:event_numButton3ActionPerformed

    private void numButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numButton5ActionPerformed
        if(currentCard=="withdrawCard")
        {
            withdrawTextField.setText(withdrawTextField.getText()+"5");
        }
        else if(currentCard=="depositCard")
        {
            depositTextField.setText(depositTextField.getText()+"5");
        }
    }//GEN-LAST:event_numButton5ActionPerformed

    private void numButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numButton6ActionPerformed
        if(currentCard=="withdrawCard")
        {
            withdrawTextField.setText(withdrawTextField.getText()+"6");
        }
        else if(currentCard=="depositCard")
        {
            depositTextField.setText(depositTextField.getText()+"6");
        }
    }//GEN-LAST:event_numButton6ActionPerformed

    private void numButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numButton7ActionPerformed
        if(currentCard=="withdrawCard")
        {
            withdrawTextField.setText(withdrawTextField.getText()+"7");
        }
        else if(currentCard=="depositCard")
        {
            depositTextField.setText(depositTextField.getText()+"7");
        }
    }//GEN-LAST:event_numButton7ActionPerformed

    private void numButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numButton9ActionPerformed
        if(currentCard=="withdrawCard")
        {
            withdrawTextField.setText(withdrawTextField.getText()+"9");
        }
        else if(currentCard=="depositCard")
        {
            depositTextField.setText(depositTextField.getText()+"9");
        }
    }//GEN-LAST:event_numButton9ActionPerformed

    private void numButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numButton8ActionPerformed
        if(currentCard=="withdrawCard")
        {
            withdrawTextField.setText(withdrawTextField.getText()+"8");
        }
        else if(currentCard=="depositCard")
        {
            depositTextField.setText(depositTextField.getText()+"8");
        }
    }//GEN-LAST:event_numButton8ActionPerformed

    private void numButton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numButton0ActionPerformed
        if(currentCard=="withdrawCard")
        {
            withdrawTextField.setText(withdrawTextField.getText()+"0");
        }
        else if(currentCard=="depositCard")
        {
            depositTextField.setText(depositTextField.getText()+"0");
        }
    }//GEN-LAST:event_numButton0ActionPerformed

    private void numButtonDecimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numButtonDecimalActionPerformed
        if(currentCard=="withdrawCard")
        {
            withdrawTextField.setText(withdrawTextField.getText()+".");
        }
        else if(currentCard=="depositCard")
        {
            depositTextField.setText(depositTextField.getText()+".");
        }
    }//GEN-LAST:event_numButtonDecimalActionPerformed

    private void numButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numButtonClearActionPerformed
        if(currentCard=="withdrawCard")
        {
            withdrawTextField.setText("");
        }
        else if(currentCard=="depositCard")
        {
            depositTextField.setText("");
        }
    }//GEN-LAST:event_numButtonClearActionPerformed

    private void depositButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositButtonActionPerformed
            CardLayout cLayout= (CardLayout)mainPanel.getLayout(); 
            cLayout.show(mainPanel,"depositCard");
            currentCard="depositCard";
            //setting these both to false, because we are about to deposit
            depositButton.setEnabled(false);
            withdrawButton.setEnabled(false);
            //setting all the number buttons to true
            enterButton.setEnabled(true);
            numButton0.setEnabled(true);
            numButton1.setEnabled(true);
            numButton2.setEnabled(true);
            numButton3.setEnabled(true);
            numButton4.setEnabled(true);
            numButton5.setEnabled(true);            
            numButton6.setEnabled(true);
            numButton7.setEnabled(true);
            numButton8.setEnabled(true);
            numButton9.setEnabled(true);
            numButtonDecimal.setEnabled(true);
            numButtonClear.setEnabled(true);
            //and make a clean textfield to fill out
            depositTextField.setText("");
    }//GEN-LAST:event_depositButtonActionPerformed

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }
    private boolean isValidAccount(String accNum, String password)
    {
        //Where the validation is
        for (int i = 0; i < accounts.length; i++) {
             acc =accounts[i];
             //if the account number and password is equals to what has been passed, then return true
             if (acc.getAccNum().equals(accNum) && (acc.getPassword().equals(password)))
            {
                return true;
            }
           
        }
        return false;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AfterCashInPanel;
    private javax.swing.JPanel AfterCashOutPanel;
    private javax.swing.JPanel BalanceInquiryPanel;
    private javax.swing.JPanel DepositPanel;
    private javax.swing.JPanel LoginPanel;
    private javax.swing.JPanel WithdrawPanel;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel cashInAmountLabel;
    private javax.swing.JLabel cashOutAmountLabel;
    private javax.swing.JButton depositButton;
    private javax.swing.JLabel depositLabel;
    private javax.swing.JTextField depositTextField;
    private javax.swing.JLabel depositedLabel;
    private javax.swing.JButton enterButton;
    private javax.swing.JLabel errorText;
    private javax.swing.JLabel errorText1;
    private javax.swing.JButton inquiryBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel newBalanceLabel;
    private javax.swing.JLabel newBalanceLabel1;
    private javax.swing.JButton numButton0;
    private javax.swing.JButton numButton1;
    private javax.swing.JButton numButton2;
    private javax.swing.JButton numButton3;
    private javax.swing.JButton numButton4;
    private javax.swing.JButton numButton5;
    private javax.swing.JButton numButton6;
    private javax.swing.JButton numButton7;
    private javax.swing.JButton numButton8;
    private javax.swing.JButton numButton9;
    private javax.swing.JButton numButtonClear;
    private javax.swing.JButton numButtonDecimal;
    private javax.swing.JPasswordField passwordField1;
    private javax.swing.JLabel setLimitLabel;
    private javax.swing.JTextField setLimitTextField;
    private javax.swing.JTextField textField1;
    private javax.swing.JLabel textLabel1;
    private javax.swing.JLabel textLabel10;
    private javax.swing.JLabel textLabel11;
    private javax.swing.JLabel textLabel2;
    private javax.swing.JLabel textLabel3;
    private javax.swing.JLabel textLabel4;
    private javax.swing.JLabel textLabel5;
    private javax.swing.JLabel textLabel6;
    private javax.swing.JLabel textLabel7;
    private javax.swing.JLabel textLabel8;
    private javax.swing.JLabel textLabel9;
    private javax.swing.JButton withdrawButton;
    private javax.swing.JTextField withdrawTextField;
    private javax.swing.JLabel withdrawnLabel;
    private javax.swing.JLabel withdrawnLabel1;
    private javax.swing.JLabel withdrawnLabel3;
    // End of variables declaration//GEN-END:variables
}
